name: Build and Run

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install boost
      run: sudo apt-get install libboost-thread-dev
    
    - name: build
      run: g++ -fprofile-arcs -ftest-coverage -std=c++11 -Wall -Wextra -pthread -o receiver BMS_Receiver/BMS_Receiver_Main.cpp BMS_Receiver_Core/*.cpp
      
 #   - name: run
 #     run: ./receiver
      
