name: Build and Run

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install coverage
          pip install numpy
      
      - name: Install boost
        run: sudo apt-get install libboost-thread-dev
    
      - name: build
        run: g++ -fprofile-arcs -ftest-coverage -std=c++11 -Wall -Wextra -pthread -o receiver BMS_Receiver/BMS_Receiver_Main.cpp BMS_Receiver_Core/*.cpp
        
      - name: Sender - Receiver pipe
        run: python BMS_Sender.py | ./receiver
      
