name: Build and Run

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
    
    - name: install coverage tool
      run: sudo apt-get install -y gcovr
   
    - name: Install boost
      run: sudo apt-get install libboost-thread-dev
      
    - name: build
      run: g++ -fprofile-arcs -ftest-coverage -std=c++11 -Wall -Wextra -pthread -o receiver_test BMS_Test/*.cpp BMS_Receiver_Core/*.cpp
      
    - name: run
      run: ./receiver_test
      
    - name: collect coverage
      run: gcovr -r . --html --html-details -o coverage.html

    - name: create coverage artifact
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: ./*.html
        retention-days: 1
